import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Banner from "../components/banner";
import Card from "../components/card";
import coffeeStoreData from "../data/coffee-stores.json";
import fetchCoffeeStores from "../data/apiFetch";
import {Grid} from "@mui/material";
import useTrackLocation from "../hooks/use-track-location";
import {useState,useEffect} from "react";


export async function getStaticProps(context){
	let data = await fetchCoffeeStores();

	return {
		props:{
			coffeeStores:data
		}
	}
};
export default function Home(props) {
	
	const {handleTrackLocation,latLong,locationErrorMsg,isFindingLocation}= useTrackLocation();

	

	const handleOnClick= ()=>{
		console.log("hi banner button");
		console.log({latLong,locationErrorMsg});
		handleTrackLocation();
	}

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffe Connoiseur</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
	  		<Banner  buttonText={isFindingLocation?"locating...":"View stores nearby"} handleClick={handleOnClick}/>
				{locationErrorMsg!==""&&`Something went wrong:${locationErrorMsg}`}
				<div className={styles.heroImage}>
					<Image src="/static/hero.png" width={200} height={200} alt="hero image"/>
				</div>
			<h2 className={styles.heading2}>Toronto stores</h2>

				
					<Grid container spacing={5}>
						{props.coffeeStores.map((store,index)=>{
						return(
						<Grid item xs={6} md={4} key={index}>	
						<Card 
						className={styles.card}
						key={store.fsq_id}
						name={store.name}
						imgUrl={store.imgUrl}
						href={`/coffee-store/${store.name}`}
						/>
						</Grid>
						
						)
					})}
					</Grid>
					

				
      </main>


    </div>
  )
}
